version: '3.8'

tasks:
  lint:
    desc: 'Lint and type check the code'
    cmds:
      - ruff format
      - ruff check --fix
      - mypy concert_db/ tests/

  test:
    desc: 'Run tests'
    cmd: pytest

  app:
    env:
      ENVIRONMENT: development
    desc: 'Run the application'
    cmd: python -m concert_db.app

  all:
    desc: 'Run all checks'
    deps: [lint, test]
