version: '3.8'

tasks:
  lint:
    desc: 'Lint and type check the code'
    cmds:
      - ruff format
      - ruff check --fix
      - mypy concert_db/ tests/

  test:
    desc: 'Run tests'
    cmd: pytest

  all:
    desc: 'Run all checks'
    ignore_error: true
    cmds:
      - task lint
      - task test

  app:
    env:
      ENVIRONMENT: development
    desc: 'Run the application'
    cmd: python -m concert_db.app

  seed:
    env:
      ENVIRONMENT: development
      PYTHONPATH: .
    desc: 'Seed the database with dummy data'
    cmds:
      - rm -f concert_db.sqlite
      - uv run python -m scripts.add_sample_data

  shell:
    env:
      ENVIRONMENT: development
    desc: 'Start a shell with database configured'
    cmd: ipython -i scripts/db_shell.py
